-- Camada analitica minima da Atividade 3.
-- Esta migration e aditiva, local neste gate, e nao altera as migrations 1-4.
-- O schema e propriedade do executor da migration; nenhum papel de aplicacao
-- recebe privilegio DDL. O contrato de policies fica para o gate analytical_rbac.

create schema analytics;

create table analytics.dim_source (
  source_key bigint generated by default as identity primary key,
  data_source_id uuid not null references public.data_sources(id) on delete restrict,
  source_ref text not null,
  source_name text not null,
  semantic_contract_version text not null,
  constraint dim_source_data_source_unique unique (data_source_id),
  constraint dim_source_ref_unique unique (source_ref),
  constraint dim_source_ref_safe check (
    source_ref ~ '^[a-z][a-z0-9_.:-]{0,126}$'
  ),
  constraint dim_source_name_present check (char_length(btrim(source_name)) > 0),
  constraint dim_source_contract_version_present check (
    char_length(btrim(semantic_contract_version)) > 0
  )
);

create table analytics.dim_category (
  category_key bigint generated by default as identity primary key,
  source_key bigint not null references analytics.dim_source(source_key) on delete restrict,
  normalized_category text not null,
  category_label text not null,
  category_code text not null,
  constraint dim_category_source_normalized_unique unique (source_key, normalized_category),
  constraint dim_category_source_key_unique unique (source_key, category_key),
  constraint dim_category_normalized check (
    normalized_category = lower(btrim(normalized_category))
    and char_length(normalized_category) > 0
  ),
  constraint dim_category_label_present check (char_length(btrim(category_label)) > 0),
  constraint dim_category_code_normalized check (
    category_code = lower(btrim(category_code))
    and category_code ~ '^[a-z0-9][a-z0-9_-]{0,62}$'
  )
);

create table analytics.fact_category_score (
  category_score_key bigint generated by default as identity primary key,
  source_key bigint not null references analytics.dim_source(source_key) on delete restrict,
  category_key bigint not null references analytics.dim_category(category_key) on delete restrict,
  source_record_key text not null,
  score_value numeric not null,
  is_current boolean not null default true,
  constraint fact_category_score_source_record_unique unique (source_key, source_record_key),
  constraint fact_category_score_category_source_fk foreign key (source_key, category_key)
    references analytics.dim_category(source_key, category_key) on delete restrict,
  constraint fact_category_score_record_key_sha256 check (
    source_record_key ~ '^[0-9a-f]{64}$'
  )
);

-- Consulta por fonte: count e media de registros correntes de uma origem.
--   select count(*), avg(score_value) from analytics.fact_category_score
--   where source_key = $1 and is_current;
create index fact_category_score_current_source_idx
  on analytics.fact_category_score (source_key)
  where is_current;

-- Consulta por categoria: media, minimo e maximo dos registros correntes.
--   select avg(score_value), min(score_value), max(score_value)
--   from analytics.fact_category_score where category_key = $1 and is_current;
create index fact_category_score_current_category_idx
  on analytics.fact_category_score (category_key)
  where is_current;

alter table analytics.dim_source enable row level security;
alter table analytics.dim_category enable row level security;
alter table analytics.fact_category_score enable row level security;

-- Postura deny-by-default: policies e papeis de leitura pertencem a analytical_rbac.
revoke all privileges on schema analytics from public, anon, authenticated, service_role;
revoke all privileges on table analytics.dim_source from public, anon, authenticated, service_role;
revoke all privileges on table analytics.dim_category from public, anon, authenticated, service_role;
revoke all privileges on table analytics.fact_category_score from public, anon, authenticated, service_role;
revoke all privileges on sequence analytics.dim_source_source_key_seq from public, anon, authenticated, service_role;
revoke all privileges on sequence analytics.dim_category_category_key_seq from public, anon, authenticated, service_role;
revoke all privileges on sequence analytics.fact_category_score_category_score_key_seq from public, anon, authenticated, service_role;

-- O futuro transformador precisa apenas consultar e fazer upsert; nao recebe
-- DELETE, TRUNCATE, DDL ou acesso a payload/raw por meio deste schema.
grant usage on schema analytics to service_role;
grant select, insert, update on table analytics.dim_source to service_role;
grant select, insert, update on table analytics.dim_category to service_role;
grant select, insert, update on table analytics.fact_category_score to service_role;
grant usage on sequence analytics.dim_source_source_key_seq to service_role;
grant usage on sequence analytics.dim_category_category_key_seq to service_role;
grant usage on sequence analytics.fact_category_score_category_score_key_seq to service_role;
