from __future__ import annotations

import hashlib
import re
import unittest
from pathlib import Path

from sheets_supabase_sync.artifacts import scan_secrets


ROOT = Path(__file__).parents[2]
MIGRATIONS = ROOT / "supabase" / "migrations"
PATH = MIGRATIONS / "20260903120000_add_analytics_star_schema.sql"
APPLIED_DIGESTS = {
    "20260804000000_initial_isolated_institution_schema.sql": "53f6326e1c50e9ddd6c50037e40d00ad7afc26c290fc53e64ebd1358fdae2f5d",
    "20260806120000_add_raw_current_state.sql": "c3bd0000f19627fd21fe970f1aa06df801e99c195a5202f790ca09cfc0bcf06d",
    "20260811150000_make_raw_import_event_only.sql": "43a0eba90a8665699ff2499966ca5492899a03d62929487fae8ee9bb6bb17ef1",
    "20260825120000_add_retention_controls.sql": "debcd796f04e8513861554f16ae2eb3313e849249b8cd3d24c6fea05ebe91fcc",
}


def migration_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


class AnalyticsSchemaMigrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.sql = PATH.read_text(encoding="utf-8").lower()

    def test_is_the_fifth_incremental_migration_and_preserves_applied_history(self) -> None:
        migrations = sorted(MIGRATIONS.glob("*.sql"))
        self.assertEqual(5, len(migrations))
        self.assertEqual(PATH, migrations[4])
        for name, expected_digest in APPLIED_DIGESTS.items():
            self.assertEqual(expected_digest, migration_digest(MIGRATIONS / name), name)

    def test_creates_only_the_analytics_star_schema_objects(self) -> None:
        self.assertIn("create schema analytics", self.sql)
        for table in ("dim_source", "dim_category", "fact_category_score"):
            self.assertIn(f"create table analytics.{table}", self.sql)
        self.assertNotIn("create table public.", self.sql)
        self.assertNotIn("alter table public.", self.sql)
        self.assertNotIn("create policy", self.sql)

    def test_source_dimension_has_safe_lineage_without_external_source_data(self) -> None:
        for column in ("source_key bigint generated by default as identity primary key", "data_source_id uuid not null", "source_ref text not null", "source_name text not null", "semantic_contract_version text not null"):
            self.assertIn(column, self.sql)
        self.assertIn("references public.data_sources(id) on delete restrict", self.sql)
        self.assertIn("unique (data_source_id)", self.sql)
        self.assertIn("unique (source_ref)", self.sql)
        self.assertIn("dim_source_ref_safe", self.sql)
        for forbidden in ("spreadsheet_id", "sheet_name", "payload_json", "source_url"):
            self.assertNotIn(forbidden, self.sql)

    def test_category_dimension_is_source_scoped_and_not_historical(self) -> None:
        for column in ("category_key bigint generated by default as identity primary key", "normalized_category text not null", "category_label text not null", "category_code text not null"):
            self.assertIn(column, self.sql)
        self.assertIn("unique (source_key, normalized_category)", self.sql)
        self.assertIn("unique (source_key, category_key)", self.sql)
        self.assertIn("normalized_category = lower(btrim(normalized_category))", self.sql)
        self.assertNotIn("valid_from", self.sql)
        self.assertNotIn("valid_to", self.sql)

    def test_fact_preserves_grain_and_source_category_consistency(self) -> None:
        for column in ("category_score_key bigint generated by default as identity primary key", "source_record_key text not null", "score_value numeric not null", "is_current boolean not null default true"):
            self.assertIn(column, self.sql)
        self.assertIn("unique (source_key, source_record_key)", self.sql)
        self.assertIn("foreign key (source_key, category_key)", self.sql)
        self.assertIn("references analytics.dim_category(source_key, category_key) on delete restrict", self.sql)
        self.assertIn("source_record_key ~ '^[0-9a-f]{64}$'", self.sql)
        self.assertNotIn("source_row_number", self.sql)
        self.assertNotIn("business_key", self.sql)
        self.assertNotIn("row_key_hash", self.sql)
        self.assertNotIn("payload_json", self.sql)

    def test_only_documented_nonimplicit_indexes_exist(self) -> None:
        indexes = set(re.findall(r"create index (\w+)", self.sql))
        self.assertEqual(
            {"fact_category_score_current_source_idx", "fact_category_score_current_category_idx"},
            indexes,
        )
        self.assertIn("where is_current", self.sql)

    def test_rls_and_least_privilege_are_explicit(self) -> None:
        for table in ("dim_source", "dim_category", "fact_category_score"):
            self.assertIn(f"alter table analytics.{table} enable row level security", self.sql)
            self.assertIn(f"revoke all privileges on table analytics.{table}", self.sql)
            self.assertIn(f"grant select, insert, update on table analytics.{table} to service_role", self.sql)
        self.assertIn("revoke all privileges on schema analytics", self.sql)
        self.assertIn("grant usage on schema analytics to service_role", self.sql)
        self.assertNotIn("to anon", self.sql)
        self.assertNotIn("to authenticated", self.sql)
        self.assertNotIn("grant delete", self.sql)
        self.assertNotIn("grant truncate", self.sql)
        self.assertNotIn("grant all", self.sql)

    def test_has_no_destructive_sql_secret_or_multitenant_field(self) -> None:
        for token in ("drop ", "truncate ", "delete from", "organization_id", "tenant_id", "postgresql://", "sb_secret_"):
            self.assertNotIn(token, self.sql)
        self.assertEqual([], scan_secrets(PATH.read_text(encoding="utf-8")))


if __name__ == "__main__":
    unittest.main()
